"use strict";

var STATE = {
  graph: null,
  raw: { nodes: [], edges: [], meta: {} },
  layers: {},
  providerLayerLabels: {},
  massLinkerGroupsAvailable: [],
  massLinkerGroupHubs: [],
  layerColors: {},
  linkColors: {},
  layerStyles: {},
  layerFlow: {},
  linkStrengths: {},
  linkDistances: {},
  linkWeights: {},
  linkWeightModes: {},
  linkLayerExpanded: {},
  neighborScaling: { mode: "none", directed: "undirected", weights: {} },
  layerFlowSpeed: 0.35,
  layerFlowSpacingMul: 18,
  layerFlowRadiusMul: 3.6,
  trailingHubDistance: 18,
  linkSettings: {},
  engine: {},
  solver: {},
  renderer: {},
  node: {},
  showUnlinked: false,
  noteTypes: {},
  activeNodes: [],
  activeEdges: [],
  activeIndexById: new Map(),
  activeIdsByIndex: [],
  allSearchEntries: [],
  layerStats: {},
  positionCache: new Map(),
  isFirstRender: true,
  lastAppliedDeltaRev: 0,
  deltaRecoveryInProgress: false,
  selectedNodeId: null,
  selectedPointIndex: null,
  contextNodeId: null,
  contextPointIndex: null,
  hoveredPointIndex: null,
  hoveredLinkIndex: null,
  focusedIndex: undefined,
  suggestedIds: [],
  selectedSuggestIdx: -1,
  persistHooksEnabled: true,
  flowRaf: null,
  flowStartTs: 0,
  perfRaf: null,
  perfWindowStart: 0,
  perfFrameCount: 0,
  perfFps: 0,
  nodeFxRingSelectedIndex: -1,
  nodeFxRingContextIndex: -1,
  nodeFxPingTimers: {},
  nodeFxPingUntilMs: 0,
  debugEnabled: false,
  debugMode: "off",
  uiViewportSyncTimer: null,
  lastEdgeCount: null,
  lastNodeCount: null,
  visibleGraphCounts: { notes: 0, families: 0, edges: 0 },
  hoverMonitorRaf: null,
  hoverMonitorLastTs: 0,
  pointerClientX: null,
  pointerClientY: null,
  pointerInsideGraph: false,
  pointStyleColors: new Float32Array(0),
  pointStyleSizes: new Float32Array(0),
  hoverPatchedPointIndex: null,
  lastStyleHasFocus: false,
  appliedFocusNodeMask: new Uint8Array(0),
  appliedFocusEdgeMask: new Uint8Array(0),
  appliedFocusNodeIndices: [],
  appliedFocusEdgeIndices: [],
  appliedSelectedIndex: -1,
  appliedContextIndex: -1,
  appliedHoverIndex: -1,
  pointSizeAnimRaf: null,
  pointSizeAnimTarget: null,
  basePointColors: new Float32Array(0),
  basePointSizes: new Float32Array(0),
  baseLinkColors: new Float32Array(0),
  runtimeNodeVisibleMask: new Uint8Array(0),
  runtimeEdgeVisibleMask: new Uint8Array(0),
  runtimeEdgeFlowMask: new Uint8Array(0),
  runtimeFlowActiveEdgeIndices: [],
  runtimeFlowEdgeMask: new Uint8Array(0),
  focusNodeMask: new Uint8Array(0),
  focusEdgeMask: new Uint8Array(0),
  focusAdjCache: null,
  depTreeCache: new Map(),
  depTreePendingNid: null,
  depTreeLoadingNid: 0,
  depTreeRenderState: {
    nid: 0,
    payloadRef: null,
    payloadStamp: "",
    width: 0,
    height: 0
  },
  depTreePerf: {
    windowStart: 0,
    renderCount: 0,
    renderTotal: 0,
    skipCount: 0,
    skipTotal: 0,
    rps: 0,
    sps: 0
  },
  styleDebug: {
    lastMode: "--",
    fullCount: 0,
    hoverPatchCount: 0,
    focusPatchCount: 0,
    ts: 0
  },
  hoverDebug: {
    reason: "init",
    idx: null,
    nodeId: "",
    noteType: "",
    nodeClientX: NaN,
    nodeClientY: NaN,
    pointerX: NaN,
    pointerY: NaN,
    ts: 0
  }
};

var DOM = {};
var SPACE_SIZE = 8192;
var SPACE_MARGIN = 0;
var CURVED_LINK_WEIGHT = 0.6;
var CURVED_LINK_CONTROL_DISTANCE = 0.44;
var OVERLAY_EFFECTS_ENABLED = true;
