"use strict";

var STATE = {
  graph: null,
  raw: { nodes: [], edges: [], meta: {} },
  layers: {},
  layerColors: {},
  layerStyles: {},
  layerFlow: {},
  linkStrengths: {},
  linkDistances: {},
  neighborScaling: { mode: "none", directed: "undirected", weights: {} },
  layerFlowSpeed: 0.35,
  engine: {},
  solver: {},
  renderer: {},
  node: {},
  showUnlinked: false,
  noteTypes: {},
  activeNodes: [],
  activeEdges: [],
  activeIndexById: new Map(),
  activeIdsByIndex: [],
  allSearchEntries: [],
  layerStats: {},
  positionCache: new Map(),
  isFirstRender: true,
  selectedNodeId: null,
  selectedPointIndex: null,
  hoveredPointIndex: null,
  hoveredLinkIndex: null,
  focusedIndex: undefined,
  suggestedIds: [],
  selectedSuggestIdx: -1,
  persistHooksEnabled: true,
  flowRaf: null,
  flowStartTs: 0,
  perfRaf: null,
  perfWindowStart: 0,
  perfFrameCount: 0,
  perfFps: 0,
  debugEnabled: false,
  debugMode: "off",
  uiViewportSyncTimer: null,
  lastEdgeCount: null,
  lastNodeCount: null,
  hoverMonitorRaf: null,
  pointerClientX: null,
  pointerClientY: null,
  pointerInsideGraph: false,
  pointStyleColors: new Float32Array(0),
  pointStyleSizes: new Float32Array(0),
  basePointColors: new Float32Array(0),
  basePointSizes: new Float32Array(0),
  baseLinkColors: new Float32Array(0),
  runtimeNodeVisibleMask: new Uint8Array(0),
  runtimeEdgeVisibleMask: new Uint8Array(0),
  focusNodeMask: new Uint8Array(0),
  focusEdgeMask: new Uint8Array(0),
  hoverDebug: {
    reason: "init",
    idx: null,
    nodeId: "",
    noteType: "",
    hitRadius: NaN,
    dist: NaN,
    dx: NaN,
    dy: NaN,
    nodeClientX: NaN,
    nodeClientY: NaN,
    pointerX: NaN,
    pointerY: NaN,
    ts: 0
  }
};

var DOM = {};
var SPACE_SIZE = 8192;
var SPACE_MARGIN = 0;
var CURVED_LINK_WEIGHT = 0.6;
var CURVED_LINK_CONTROL_DISTANCE = 0.44;
var OVERLAY_EFFECTS_ENABLED = true;
